print("hello world")
print ("Five is greater than two!")
print ("Have a good day.")
print ("Python is fun!")
print ("Hello, How are you doing today.")
print ("How is the weather over there. Trust you are enjoying your stay at sheffiled hallam university and the environment generally.")
print ("Hows the lecture hope you settling in")
print ('Yes.Thank you for asking.')
print ('The lecturer Jackie is an amazing lecturer.')
print ("I want to print on the same line,")
print (10)
print (5 +10)
print ('I hope to get my driving licences from the united-kingdom government so i can start driving back here') 